### ISSUE TITLE
关于函数sum_eik

### ISSUE THREAD

**Issue by lixuliang** [lijunsun/probabilistic_tucker_transport#1]
您好，我是来自中山大学的研究生，您的文章《Understanding urban mobility patterns with a probabilistic tensor factorization framework》给了我们非常大的启发，我们曾尝试用浮动车数据浮复现这一算法。在看到您的代码之后，现在我们想对比一下算法的结果是否有差异。然而我们在应用EM_tucker.m时遇到一个问题，您在子函数中调用sum_eik函数，然而我们并不知道这一函数具体对应的算法，也没有查到相应的package，不知道您是否可以告知这一函数对应的内容？
另外，根据我们对程序的理解，EM_tucker应该是您的概率张量分解模型的主程序，EM_algo_MRT应该是测试单天的结果，以及EM_algo是CP分解的主程序？不知道我们的理解是否正确？
非常希望能收到您的回复，会对我们的研究有很大的指导作用，非常感谢
敬颂师祺

**Comment by lijunsun** [comment]
sum_eik uploaded.

**Comment by lixuliang** [comment]
thank you very much
